version: '4'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'tsc && node build/index.js'
    env_file: .env
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: inforens
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
    volumes:
      - .dbdata:/var/lib/postgresql
    ports:
      - 15432:5432
